### ISSUE TITLE
Is it possible to configure it to automatically opens popup menu for completions when I enter characters?

### ISSUE THREAD

**Issue by originalrusyn** [cwfoo/vim-text-omnicomplete#3]
Is it possible to configure it to automatically opens popup menu for completions when I enter characters? Or could you please clarify how to do it with https://github.com/vim-scripts/AutoComplPop ?

**Comment by cwfoo** [comment]
> Is it possible to configure it to automatically opens popup menu for completions when I enter characters?

This functionality is well outside the scope of this plugin. All that this plugin does is provide an OmniComplete backend (i.e. it reads the text in your buffer and returns a list of completion candidates to Vim; it does not handle the display of completion menus).

Nevertheless, I can give you some pointers:

1. If you want to use AutoComplPop, take a look at `:help g:acp_behavior`.
    (From what I see, `"command"` should be `"\<C-x>\<C-o>"`, `"repeat"` should be `0`, and `"meets"` should be a function that always returns `1`. I could be wrong, and I can't help you much in this area since I am unfamiliar with AutoComplPop.)
2. Instead of using AutoComplPop, you could use an actively maintained and well-documented plugin such as [vim-mucomplete][1]. AutoComplPop has been abandoned for more than a decade by now. I use vim-mucomplete to achieve the functionality you describe.

  [1]: https://github.com/lifepillar/vim-mucomplete
